<?php
$this->render('page-controller/about/sidebar', array('active' => 'overview'));
?>

<h1>关于</h1>

<p>

    Zend框架2是一个开源框架,使用<a href="http://www.php.net">PHP 5.3</a> +开发web应用程序和服务。Zend框架2使用100%面向对象代码和利用大多数PHP 5.3的新特性,即名称空间、延迟静态绑定,lambda函数和闭包。


</p>

<p>
    从Zend Framework 1 到Zend Framework 2,一个成功的PHP开发框架已有1500万下载。
</p>

<p>

    Zend框架2的组成结构是独一无二的;每个组件被设计与其他部件数的依赖关系。
    ZF2遵循SOLID面向对象的设计原则。
    这样的松耦合结构可以让开发人员使用他们想要的任何部件。我们称之为“松耦合”的设计。我们支持
    <a href="http://pear.php.net/manual/en/pyrus.php">Pyrus</a>
    and <a href="http://getcomposer.org/">Composer</a>
    作为一个整体的安装和依赖跟踪机制，并为每个组件，进一步增强这种设计。
</p>

<p>
    We use <a href="http://www.phpunit.de">PHPUnit</a> to test our code and <a href="http://travis-ci.org/#!/zendframework/zf2">Travis CI</a> as a Continuous Integration service.
    我们使用<a href="http://www.phpunit.de">PHPUnit</a>来测试代码和<a href="http://travis-ci.org/#!/zendframework/zf2">Travis CI</a> 作为持续集成服务
</p>

<p>

    虽然它们可以单独使用，Zend框架2组件的标准库结合时，形成一个强大的，可扩展的Web应用程序框架。此外，它提供了一个强大的，高性能的MVC实现，数据库抽象，简单易用，并实现HTML5表单呈现，验证一个表单组件，过滤使开发人员可以使用一个易于整合所有这些操作使用的，面向对象的接口。其他组件，如Zend\Authentication和Zend\Permissions\Acl中，提供用户身份验证和授权对所有常见的凭据商店
</p>

<p>
    此外，与ZendService的命名空间，实现客户端库最简单地访问，提供流行的web服务，无论您的应用程序需求是怎样，
    您都可能会找到Zend框架2组件,可以大大减少开发时间彻底以及基础测试。
</p>

<p>

    “Zend Framework 2”的主要赞助商是<a href="http://www.zend.com">Zend Technologies</a>,但许多公司贡献了组件或重大功能框架。, 如<a href="http://www.google.com">Google</a>, <a href="http://www.microsoft.com">Microsoft</a>,
    <a href="http://www.strikeiron.com">StrikeIron</a>与Zend为web服务提供的接口和其他技术，他们希望使Zend框架2开发人员使用。


</p>

<p>

    Zend框架2不能交付和支持所有这些功能，而充满活力的Zend Framework的2个社区会帮助你。社区成员，包括贡献者，让他们可以在<a href="<?php echo $this->basePath('archives') ?>">邮件列表</a>，IRC频道和其他论坛可以得到。不管你对Zend框架2有什么问题，社区始终可用来解决它。

</p>