<?php
$this->render('page-controller/about/sidebar', array('active' => 'license'));
?>
<h1>开源许可
</h1>

<p>
    Copyright (c) 2005-<?php echo date('Y') ?>, Zend Technologies USA, Inc.
    All rights reserved.
</p>
<p>
    再分配和使用源代码和二进制形式,有或没有允许修改,提供下列满足条件:
</p>
<ul>
    <li>
        以源代码必须保留未经修改的上述版权注意,该列表的条件以及其后的免责声明。
    </li>
    <li>
        以二进制形式重新发布必须保留未经修改的上述版权,注意,该列表的条件以及其后的免责声明提供的文档和/或其他材料分布。
    </li>
    <li>
        无论是美国Zend Technologies的名字,公司的名字贡献者可以用来支持或促进产品来自这个软件没有特定的书面许可。
    </li>
</ul>
<p>
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
    INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
    DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
    BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
    LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
    THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
    SUCH DAMAGE.
</p>