<?php
$this->layout()->bodyId = 'participate';
$this->layout()->active = 'participate';
$this->render('page-controller/participate/sidebar', array('active' => 'participate'));
$headTitle = $this->headTitle();
$headTitle->prepend('参与');
?>

<h1>参与</h1>

<blockquote>
    Zend Framework有很多的代码. 是一个社区在支撑.
</blockquote>

<p>
    Zend Framework有数百的贡献者和数十万用户，再次我不得不感谢这么多年来他们为这个社区提供这么多的代码，这么多的测试和文档和支持贡献。
</p>

<p>
    简单的说：我们不只是建立了一个框架,我们已经建立了一个社区。
</p>

<h3><a href="<?php echo $this->basePath('participate/contributor-guide') ?>">投稿指南</a></h3>

<p>
    学习如何有效的同我们一起促进
    <a href="<?php echo $this->basePath('participate/contributor-guide') ?>">社区贡献</a>.
</p>

<h3><a href="<?php echo $this->basePath('participate/user-groups') ?>">用户组</a></h3>

<p>
    想更多的了解Zend Framework? 想帮助别人学习? 请查找你附近的
    <a href="<?php echo $this->basePath('participate/user-groups') ?>">用户组</a>!
</p>

<h3><a href="<?php echo $this->basePath('participate/blogs') ?>">博客</a></h3>

<p>
    很多Zend Framework用户的博客是非常活跃的, 分享技术与方法. 我们可以查看到一些非常有 <a href="<?php echo $this->basePath('participate/blogs') ?>">特色的博客</a>.
</p>

<h3><a href="<?php echo $this->basePath('participate/contributors') ?>">贡献者</a></h3>

<p>
    自Zend Framework推出以来，为项目提供指导，代码，文档和其他支持的社区成员。你们将会得到机会在
    <a href="<?php echo $this->basePath('participate/contributors') ?>">贡献者列表</a>展示.
</p>

<h3><a href="http://modules.zendframework.com/" target="_blank">贡献功能模块</a></h3>

<p>
    你想在社区分享大的ZF功能模块？请先看看是否有别人写了相关模块？请参考
    <a href="http://modules.zendframework.com/" target="_blank">ZF2模块网站</a>!
</p>

<h3><a href="<?php echo $this->basePath('participate/logos') ?>">Logos</a></h3>

<p>
    你想宣传zend framework? 或者你想创建zend框架相关的话题， 我们的标志是 <a href="http://creativecommons.org/licenses/by-nc/3.0">CC BY-NC</a>
    我们的logo库是 <a href="<?php echo $this->basePath('participate/logos') ?>">logo gallery</a>.
</p>

