<?php 
$this->render('page-controller/contact/sidebar', array('active' => 'contact'));

$this->headTitle()->prepend('Contact'); 
?>
<h1>联系我们</h1>

<p>我们很乐意听到你的建议!</p>

<p>关于Zend框架的技术问题,请搜索我们的<a href="<?php echo $this->basePath('archives') ?>">档案</a>
    如果你的问题或问题没有解决,请订阅我们的<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">邮件列表</a>之一.
    你的问题将在其中的一个论坛回答要快得多。如果你正在寻找企业Zend框架的支持,<a href = "http://www.zend.com/en/services/support/zend-framework-support " >在线 </a>。

</p>

<?php if ($this->error): ?>
    <div class="alert-box alert">
        <p>

            有一个或多个服务主体与你提交。请纠正他们如下表示。
        </p>
    </div>
<?php endif ?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('contact/process'));
$send = $form->get('Send');
$send->setAttribute('class', 'button');

echo $this->form()->openTag($form);

// From
echo $this->formRow($form->get('from')->setAttribute('id', 'from'));

// Subject
echo $this->formRow($form->get('subject')->setAttribute('id', 'subject'));

// Body
echo $this->formRow($form->get('body')->setAttribute('id', 'body'));

// Captcha
echo $this->formRow($form->get('captcha')->setAttribute('id', 'captcha'));

// CSRF
echo $this->formElement($form->get('csrf')->setAttribute('id', 'csrf'));

// Send button
echo $this->formInput($send);

echo $this->form()->closeTag() ;
?>