<?php
$this->render('page-controller/about/sidebar', array('active' => 'faq-v1'));

$headTitle = $this->headTitle();
$headTitle->prepend('About');
$headTitle->prepend('FAQ ZFv1');
?>
<h1>FAQ ZFv1</h1>

<blockquote>
    关于ZF1的常见问题
</blockquote>

<dl>
<dt>Zend_Auth 与 Zend_Acl 的区别是什么?</dt>
<dd>
    <p>
        <tt>Zend_Auth</tt> 是用来验证用户身份的方法, 包括 LDAP, OpenID, 和 HTTP. 身份验证是为系统提供有效的证书. 在您的系统的过程中验证用户的身份.更多信息在Zend框架中验证和实现,
        <a href="http://framework.zend.com/manual/en/zend.auth.html">查看 <tt>Zend_Auth</tt> 文档</a>.
    </p>

    <p>
        <tt>Zend_Acl</tt> 是一个对访问控制列表(ACL)的授权，一般来说, acl列表授权特定资源给角色在您的系统上执行特定的操作. <tt>Zend_Acl</tt>
        可以支持多重继承等高级规则定义与功能角色和断言条件规则. 更多关于 <tt>Zend_Acl</tt>的信息, <a
            href="http://framework.zend.com/manual/en/zend.acl.html">查看 <tt>Zend_Acl</tt> 文档</a>.
    </p>

    <p>
        <tt>Zend_Auth</tt> 和 <tt>Zend_Acl</tt>可以一起使用来构建非常复杂的安全系统: 首先,用户用 <tt>Zend_Auth</tt>确认他们的身份, 然后用这个身份是用来分配一个或多个
        <tt>Zend_Acl</tt> 角色用户授权来使用或修改系统中的资源.
    </p>

<dt>
    我必须为Zend框架做些什么?
</dt>
<dd>
    <p>
        为促进Zend框架的发展，唯一要求是满足是我们的<a href="http://framework.zend.com/cla">个人贡献者许可协议（CLA）</a>，或者我们的<a
            href="http://framework.zend.com/ccla">企业CLA</a>。一旦你已经签署了CLA，您可以访问我们的<a
            href="http://framework.zend.com/wiki/display/ZFDEV/Home" title="Home">贡献者维基</a>上手。
    </p>

    <p>
        我们强烈推荐你阅读和理解我们的新BSD License-style许可证的条款,在Zend框架许可的部分下,包容所有的贡献。
    </p>
</dd>

<dt>我要提交到我的CLA用户是什么，我为什么要提交？</dt>
<dd>
    <p>
        这是你使用的用户名访问<a href="http://framework.zend.com/issues">issue tracker</a>, <a
            href="http://framework.zend.com/wiki">wiki</a>, <a href="http://framework.zend.com/code">code browser</a>等等，
        如果你没有一个用户名，你可以在<a href="http://framework.zend.com/issues/secure/Signup!default.jspa">这里</a>注册，
        当我们处理你的CLA时,我们需要适当的特权授予您的用户。要做到这一点,我们首先得知道您的用户名。

    </p>
</dd>

<dt>
    我应该注册一个<a href="http://framework.zend.com/cla">个人 CLA</a> 还是 <a href="http://framework.zend.com/ccla">企业 CLA</a>?
</dt>

<dd>
    <p>

        如果你贡献的代码作为一个个人，而不是你在公司工作的一部分，你应该在注册<a href="http://framework.zend.com/cla">个人 CLA</a>，反之，你应该在注册一个<a
            href="http://framework.zend.com/ccla">企业 CLA</a>，
        而且你应该提交一份企业CLA与所有同事的姓名,当你觉得能为项目做出了贡献的时候。

    </p>
</dd>

<dt>我应该在了解 Zend Framework CLA 之前提交吗？</dt>
<dd>
<p>通过签署CLA,贡献源代码提供了一个版权，Zend许可证使用他或她提交的源代码Zend框架项目。通过这样做,贡献者不放弃他或她自己的权利或他或她的版权和自己的代码,但是为我们提供了一个版权许可。此外,CLA的目的是明确知识产权的条款，是让Zend框架更好的保护贡献者的知识,而不是为了侵犯了别人的知识产权,让他或她有权做出这样的贡献，。</p>
</dd>

<dt>为什么在Zend Framework项目有CLA呢？</dt>
<dd>
    <p> 我们减轻公司在Zend框架的用户的需求中可能侵犯知识产权的版税或费用，
          无论是个人或公司, 特别是公司把他们重要的业务或产品建立在Zend框架上
        CLA保护所有用户，包括个人、中小企业和大型企业。   Zend框架CLA有助于确保代码和其他IP在Zend框架仍然是免费的。
    </p>

<dt>I am a minor (under 18 years of age). Who should sign my CLA?</dt>
<dd>
    <p>
        　CLA18岁以下的贡献者的应该签署贡献者和贡献者的法定监护人
    </p>
</dd>

<dt>什么样的贡献，要求我提交一份CLA？什么样的贡献可以不提交CLA？
</dt>
<dd>
    <p>
        你必须签署一份CLA在Zend框架可以接受任何构成知识产权的内容。这包括任何可能携带版权或专利。这包括代码,补丁,测试,文档,甚至在<a href="http://framework.zend.com/wiki/display/ZFPROP/Home" title="Home">wiki</a>.提案提交。你不需要在
        在我们的 <a href="http://framework.zend.com/issues">issue tracker</a>,或<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists"> mailing lists</a>
        提交一个CAL报告bug。可以包含代码的电子邮件到发送到邮件列表,但是你的代码不能被纳入Zend框架,除非它被提交到基础CAL。
    </p>
</dd>

<dt>
    我已经提交了CLA,现在我如何促进Zend框架?
</dt>
<dd>
    有很多促进Zend框架的方法。主要是通过 <a href="http://framework.zend.com/wiki/display/ZFPROP/Home" title="Home">投票</a>促进ZF的发展。大多数代码贡献者也提交bug修复和测试。另一个有价值的贡献是人工翻译和其他形式的文档。贡献者也可能用他们的时间更新或添加<a href="http://framework.zend.com/wiki">wiki</a>,评论和在我们的<a href="http://framework.zend.com/issues">问题跟踪器</a>投票。无论你如何计划作出贡献,开始贡献最好的地方是我们的向导。
    </p>
</dd>


<dt>Zend框架是怎样实现ORM的?</dt>

<dd>
    <p>
        对象关系映射(orm)框架,包括数据访问、存储库,
       身份映射,和更多的组件。
        我们觉得有意义让ORM专家编写此类软件,和允许在Zend框架整合这些解决方案。
    </p>
</dd>

<dt>
    我想使用SQL函数或在一份声明中我生成与Zend_Db_Select对象进行计算。我怎样才能做到这一点？
</dt>

<dd>
    <p>
        　实际上,默认情况下,如果你的表达式包含括号,<tt> Zend_Db_Select </tt>将声明　　作出适当。然而,如果它不,或者你有问题,你可以使用<tt> Zend_Db_Expr </tt> 　　显式地创建表达式:
    </p>

        <pre class="highlight"><code>/* Build the SQL:
                * SELECT p."product_id", p.cost * 1.08 AS cost_plus_tax
                * FROM "products" AS p
                */
                $select = $db-&gt;select()
                -&gt;from(array('p' =&gt; 'products'),
                array(
                'product_id',
                'cost_plus_tax' =&gt; new Zend_Db_Expr('p.cost * 1.08'),
                ));
            </code></pre>

<dt>我怎么能自定义的外观形式由<tt> Zend_Form </tt> ?</dt>

<dd>
    <p>
        你可能找<a
            href="http://devzone.zend.com/article/3450-Decorators-with-Zend_Form">decorators</a>。所有形式和表单元素Zend_Form使用修饰符来呈现他们的输出。
    </p>
</dd>

<dt>我如何添加额外的HTML表单元素(如链接)我吗?
    </dt>
<dd>

    <p>
        这可以很容易地通过使用修饰符。例如使用修饰符描述。重要的是要注意你需要关掉逃离装饰器的输出</p>

            <pre class="highlight"><code>$element-&gt;setDecorators(array(
                    array('ViewHelper'),
                    array('Description', array('escape' =&gt; false)),
                    array('Errors'),
                    array('HtmlTag', array('tag' =&gt; 'dd')),
                    array('Label', array('tag' =&gt; 'dt')),
                    ));</code></pre>

    <p>现在,您可以使用以下添加额外的HTML元素</p>

            <pre class="highlight"><code>$element-&gt;setDescription(
                    '&lt;strong&gt;This contains HTML that will actually be parsed by the browser, not escaped&lt;/strong&gt;'
                    );</code></pre>

</dd>

<dt>Why can't <tt>Zend_Form</tt> render my <tt>File</tt> element without errors?
    为什么不能用<tt>Zend_Form</tt>来渲染我没有错元素的误文件？
</dt>

<dd>
    <p>
        文件元素需要一个特殊的文件装饰,添加默认情况下。当你设定你自己的修饰符　　文件元素,你删除默认的修饰符。例如</p>

            <pre class="highlight"><code>$element-&gt;setDecorators(array(
                    array('ViewHelper'),
                    array('Errors')
                    ));</code></pre>

    <p>
        您应该使用一个文件文件元素的装饰而不是<tt>ViewHelper</tt>,像这样:
    </p>

            <pre class="highlight"><code>$element-&gt;setDecorators(array(
                    array('File'),
                    array('Errors')
                    ));</code></pre>

</dd>

<dt>我怎么能发现如果一个可选的文件已经上传?</dt>
<dd>

    <p>The <tt>receive()</tt> method will return <tt>true</tt> for file elements that are not required. The reason is
        that you said "the file can be omitted, and that's ok for me". The <tt>receive()</tt> method will return false
        only in the event of a failure.
        receive()方法将对文件不需要的元素返回true。原因是“文件可以省略”。receive()方法只有在发生故障时返回错误。


    </p>

    <p>仍然有几种方法可以检测是否已经上传文件:</p>

    <ul>
        <li>使用isUploaded它返回一个布尔值</li>
        <li>
            在这种情况下使用给getFileName返回null(请注意,您必须使用最新版本)
        </li>
        <li>
            用getFileInfo将一个空的文件密钥和国旗“isUploaded”设置为false
        </li>
    </ul>

</dd>

<dt>
    Zend框架需要哪个版本的PHP?
</dt>

<dd>

    <p
        Zend框架需要PHP 5.2.11和。一些Zend框架组件可能与早期版本的PHP,但这些组件测试和支持5.2.11和。有关更多信息,请参见 <a
            href="http://framework.zend.com/manual/en/requirements.html">附件</a> 要求。
    </p>

</dd>

<dt>Zend框架支持PHP 4吗?</dt>

<dd>
    <p>No. Zend Framework was built to use all of the sophisticated object oriented features of PHP 5 and take advantage
        of significant performance and security enhancements.
        　不。Zend框架使用PHP 5的特性和利用复杂的面向对象以及显著的性能和安全性。

    </p>

    <p>
        另一个考虑是ZF将运行在支持平台。PHP社区在2008-01-01正式停止支持PHP 4,而且在2008-08-08也没有PHP 4的关键安全更新。

    </p>

    <p>这些因素等等,相信我们,PHP 5 Zend框架建立在ZF上最好的平台和应用程序　　。</p>
</dd>


<dt>>模型在ZF的MVC实现在哪里?</dt>

<dd>
    <p>模型组件可能显著不同的责任,从一个MVC应用程序的数据存储。ZF社区没有定义一个模型接口,类或其他形式主义仅仅是因为我们想避免引入限制没有重要的附加值。</p>

</dd>

<dt>ZF是一个组件库或框架吗?</dt>

<dd>

    <p>　简单的回答:两个。Zend框架提供了大多数web应用程序所需的所有组件在一个　　分布。但Zend框架组件也松散耦合,使其易于使用的只是其中一部分　　web应用程序中的组件,甚至与其他框架!使用这种随意使用架构,我们是来旅游的　　实现功能常见的整体框架。事实上,我们目前正在研究　　工具组件的1.8版本,这将使它更简单的使用ZF构建应用程序组件, 　　不会牺牲现有ZF组件的随意使用性质。这是一个体现随意使用　　Zend框架的架构工具组件本身可以独立使用。.</p>

</dd>

<dt>我该怎样才能让所有i18n-aware组件了解Zend_Translate对象?</dt>

<dd>
    <p>各种组件都知道（即接受<tt>的一个Zend_Translate</tt>的对象），其中包括：</p>

    <ul>
        <li>Zend_View_Helper_Translate</li>
        <li>Zend_Validate_*</li>
        <li>Zend_Form</li>
    </ul>

    <p>　让他们都使用相同的<tt> Zend_Translate </tt>实例,简单地将它在注册表的关键　　“Zend_Translate”:</p>


    <pre class="highlight"><code>Zend_Registry::set('Zend_Translate', $translate);</code></pre>

</dd>

<dt>我怎么能到处都使用相同的语言环境吗?</dt>

<dd>

    <p>与ZF1.7应用程序语言环境支持。你可以在引导文件如下:</p>

            <pre class="highlight"><code>$locale = new Zend_Locale('en');
                    Zend_Registry::set('Zend_Locale', $locale);</code></pre>


    <p>从现在起，所有语言环境的组件将使用存储在注册表中的Locale对象，只要你不
                手动给另一个.</p>

</dd>

<dt>为什么我的日期格式错了？为什么我得到了错误的年份值？</dt>

<dd>

    <p>当在代码中使用自己的格式，你可以来到一个情况下，你获得例如2009年12月29日，但你
                可能获得2008年12月29日。</p>

    <p>有一年的区别:2009年而不是2008年。您应该使用小写格式不变。看到这个例子:</p>

    <pre class="highlight"><code>$date-&gt;toString('dd.MM.yyyy');</code></pre>

    <p>注意下小写“y”使得真正的和输出的差异</p>

</dd>

<dt>我如何在一个简单的方法调试Zend_Date?</dt>
<dd>
    <p>
        当你认为你都可以从使用Zend_Date再输出错了，它往往需要看到什么使用Zend_Date
                确实在内部使用。
    </p>

    <p>
        嗯. .var_dump Zend_Date不是真正helpfull,但你可以简单地使用getIso()。这种格式有各种日期信息:
    </p>

    <pre class="highlight"><code>$date-&gt;getIso(); // could return '2009-10-21T15:00:02+01:00'</code></pre>

    <p>
        注意,使用toString()和输出的部分只有日期不显示所有需要的信息。有　　可能是一个错误的使用时区或DST改变压制的toString()但显示getIso()。
    </p>


<dt>模型在哪里?</dt>

<dd>
    <p>模型与视图和控制器组件,组件可能显著不同的责任和数据存储从一个MVC应用程序到下一个。它应该代表抽象的应用程序。Zend框架的社区没有定义一个模型接口,类,或其他形式主义,因为我们没有发现足够的附加价值来证明限制构成一个模型</p>

</dd>

<dt>How can I retrieve the view object within a plugin or arbitrary code?</dt>

<dd>
    <p>
        　ZF助手叫ViewRenderer默认使用一个行动。这个动作帮助实例化和存储Zend_View对象,随后注入其他对象。对象存储在视图　　ViewRenderer属性的观点。你可以得到ViewRenderer实例,从而视图实例,与行动辅助代理:
    </p>

            <pre class="highlight"><code>$viewRenderer =
                    Zend_Controller_Action_HelperBroker::getStaticHelper('viewRenderer';
                    $view = $viewRenderer-&gt;view;
                </code></pre>


    <p>然而,如果你访问视图在调度过程的早期——前一个动作实际上是分配的例子,那么您可能需要先初始化视图:</p>

    <div class="code">
                <pre class="highlight"><code>if (!isset($viewRenderer-&gt;view)) {
                        $viewRenderer-&gt;initView();
                        }
                        $view = $viewRenderer-&gt;view;
                    </code></pre>

        <p>
            如果您正在使用和Zend_Layout已经初始化,您可以访问更多的视图对象简要说明:
        </p>

        <pre class="highlight"><code>$view = Zend_Layout::getMvcInstance()-&gt;getView();</code></pre>

        <p>这个代理ViewRenderer和执行上面所有的步骤。</p>

</dd>

<dt>　　我使用ContextSwitch或AjaxContext视图助手和接收指示error.ajax.phtml异常　　视图脚本失踪,我做错了什么?”
</dt>

<dd>
    <p>
        ContextSwitch使假设(a)你不调用< tt > _forward()< / tt >,(b)你的应用程序代码将不会抛出异常。如果你看到上面的错误,你的代码抛出异常但是仍在上下文中,ViewRenderer只是想加载当前视图脚本从ErrorController上下文。
    </p>

    <p>
        改变现状的最简单的方法是<tt> ErrorController::errorAction()</tt>定义视图　　脚本后缀,如下:
    </p>

<pre class="highlight"><code>class ErrorController extends Zend_Controller_Action
        {
        public function errorAction()
        {
        $this-&gt;_helper-&gt;viewRenderer-&gt;setViewSuffix('phtml');
        // ...
        }
        }
    </code></pre>

</dd>

<dt>我使用Apache,urlencoded斜线通过$ _GET或作为URL参数传递,我得到的404错误!</dt>

<dd>

    <p>
        Apache默认情况下不允许urlencoded斜杠(即。“% 2 f”)在URL路径部分或查询字符串。这个特性　　可以通过禁用启用“AllowEncodedSlashes指令”:
    </p>

    <pre class="highlight"><code>打开 AllowEncodedSlashes </code></pre>

    <p>然而,这个指令必须设置在服务器范围的(httpd . conf)或虚拟主机的级别。</p>

    <p>有关更多信息,<a href="http://httpd.apache.org/docs/2.0/mod/core.html#allowencodedslashes">阅读　　AllowEncodedSlashes文档</a>.</p>

</dd>

<dt>Lucene是什么?</dt>
<dd>
    <p>
        <a href="http://lucene.apache.org/java/docs/index.html">Lucene < / >是一个高性能、全功能的文本搜索引擎,利用一个开放的、二进制格式存储搜索索引和查询一个标准化的格式对索引查询。Lucene最初是用Java编写的Apache项目 <tt>Zend_Search_Lucene</tt>
            是一个提供完整的PHP实现二进制兼容Java Lucene。
    </p>
</dd>

<dt>我可以用<tt> Zend_Search_Lucene </tt>搜索我的Java Lucene-generated索引吗? </dt >
<dd>
    <p>
        是的!事实上,Zend Framework站点使用Java创建的索引开发工具<tt> Zend_Search_Lucene </tt > 提供全站搜索。
    </p>
</dd>

<dt>
    我可以使用工具,如<a href="http://www.getopt.org/luke/">Luke</a> 来<tt>生成的索引Zend_Search_Lucene </tt > ?
</dt>
<dd>
    <p>是的！我们经常使用luke来检查我们的<tt>的Zend_Search_Lucene</tt> - 生成索引的开发和
                诊断。</p>
</dd>


<dt>Why are client libraries for web services such as Akismet, Amazon, Audioscrobbler, Delicious, Flickr, Nirvanix,
    Simpy, StrikeIron, and Yahoo! part of the Zend Framework standard library?
</dt>

<dd>
    <p>
        　Zend框架被设计来解决web应用程序开发中最常见的问题。Web服务是今天的web开发环境的一个重要部分。以至于我们的许多用户使用我们的web服务客户服务,比如亚马逊ECS,Akismet,要求采取更多infrastructure-oriented之前如Zend_Registry和Zend_Log组件。因为这些web服务在今天的发挥如此重要的作用web应用程序中,我们认为他们“一等公民”ZF。
    </p>
</dd>

<dt>　我试着发送一个“退订”邮件给所有ZF邮件列表,但我还是从这些列表获得消息。我必须做些什么来阻止这些邮件吗?
</dt>
<dd>
    <p>有一个“fw-all”名单,汇集了所有其他列表除了fw-announce fw-general,fw-docs,fw-svn。请发送邮件到<a href = " mailto:fw-all-subscribe@lists.zend.com"> fw-all-subscribe@lists.zend.com <a/>,以确保你没有　　订阅了这个列表。此外,请确保你的邮件退订请求从您的帐户订阅。你可能会接收列表流量不同的帐户,如果你建立了一个邮件从最初的订阅帐户。</p>

<dt>我在哪里可以重置我的密码?</dt>

<dd>
    <p>
        <a href="http://framework.zend.com/crowd">http://framework.zend.com/crowd</a></p>
</dd>

<dt>什么服务都可以从Zend为Zend框架技术吗?</dt>
<dd>
    <p>
        <a href="http://www.zend.com">Zend Technologies</a> 技术为Zend框架提供了一组全面的服务, 　　包括:
    </p>

    <ul>
        <li><a href="http://www.zend.com/en/services/support/zend-framework-support">Support</a></li>
        <li><a href="http://www.zend.com/en/services/training/course-catalog/zend-framework">Training</a></li>
        <li><a href="http://www.zend.com/en/services/consulting">Consulting</a></li>
        <li><a href="http://www.zend.com/en/services/certification/framework/">Certification</a></li>
    </ul>

</dd>
</dl>