<?php
$this->render('page-controller/about/sidebar', array('active' => 'faq'));

$headTitle = $this->headTitle();
$headTitle->prepend('About');
$headTitle->prepend('FAQ');
?>
<h1>FAQ ZFv2</h1>

<blockquote>
    关于ZF2常见问题
</blockquote>

<dl>
    <dt>为什么推出一个全新的Zend Framework</dt>
    <dd>
        我们已经从体系结构的角度检查了ZF1,以及采用开发人员案例，在大多数情况下
        我们根本无法支撑现有的案例或者体系结构需要改变。此外，ZF1的发展非常快，
        有很多地方也有类似问题的解决方案，
        Zend框架2中我们使用一组一致的编码模式和实践方案,我们已经考虑了公认的最佳实践编写高效、可靠和高性能的软件 </dd>

    <dt>
        我将在Zend框架2找到什么样的新特性 ?</dt>
    <dd>一些最突出的结果:
        <ul>
            <li>一个完全重写事件驱动的MVC</li>
            <li>
                通过组件依赖注入，来支持我们的服务定位和DIC
            </li>
            <li>一个强大的模块管理系统</li>
            <li>
                EventManager, 用于编写系统中的事件驱动, 以及在软件中引入横切关注点和创建切入点
            </li>
            <li>
                A new view layer, architected around analyzing the
                request and generating a suitable response, be it
                plain old HTML, or Atom feeds or JSON.
                一个全新的视图层，构造一个分析请求和生成一个合适的响应，无论是普通HTML或Atom feed或JSON。
            </li>
        </ul>
    </dd>

    <dt>现在Zend Framework 2.0发布,Zend框架1即将结束?</dt>
    <dd>
        当然不行!我们目前的计划完全支持Zend Framework 1至少到2014年初,包括维护和安全更新</dd>

    <dt>I have an application built with Zend Framework 1 – will I be able to migrate it to the new version?
        我已经使用Zend Framework 1构建应用程序 -我能移植到新版本吗?
    </dt>
    <dd>Absolutely. An important part of Zend Framework 2 is the migration layer that will allow ZF 1 code to run on the new ZF 2 engine, which will be made available in the future. With it, you will be able to add new ZF 2 code, and refactor existing code, at a controlled pace.
        绝对的。Zend Framework 2的一个重要组成部分是迁移层,将允许ZF 1代码运行在新的ZF 2引擎上,在未来。,你将能够添加新ZF 2代码,并重构现有代码,快速掌握
    </dd>

    <dt>
        我开始一个新项目,我应该使用哪个版本的Zend Framework?</dt>
    <dd>当然是Zend Framework 2!，它已经很稳定了
       </dd>

    <dt>
        Zend Framework 2 基于什么版本的PHP上?
        </dt>
    <dd>Zend Framework 2 是基于 PHP 5.3.
        一旦它开始由PHP社区采纳，我们希望添加支持PHP5.4</dd>

    <dt>我相信,我可以尝试最新的版本吗?
       </dt>
    <dd>You can download the latest build from <a href="http://packages.zendframework.com">http://packages.zendframework.com</a>. You can also get more information about the Zend Framework 2 project at <a href="http://framework.zend.com/zf2/">http://framework.zend.com/zf2/</a>.

        您可以从<a href="http://packages.zendframework.com">http://packages.zendframework.com</a>下载最新版本。您还可以在<a href="http://framework.zend.com/zf2/">http://framework.zend.com/zf2/</a>得到Zend Framework 2项目的更多信息。
    </dd>




</dl>