<?php
$this->layout()->bodyId = 'about';
$this->layout()->active = 'about';

$this->placeholder('sidebar')->captureStart();
?>
<ul>
    <li<?= ($this->active == 'overview' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('about') ?>">概述</a>
    </li>
    <li<?= ($this->active == 'faq' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('about/faq') ?>">FAQ</a>
    </li>
    <li<?= ($this->active == 'faq-v1' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('about/faq-v1') ?>">FAQ ZFv1</a>
    </li>
    <li<?= ($this->active == 'license' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('license') ?>">许可证</a>
    </li>
    <li<?= ($this->active == 'changelog' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('changelog') ?>">更新日志</a>
    </li>
</ul>
<?php $this->placeholder('sidebar')->captureEnd(); ?>

