<?php
$this->render('manual/page-controller/learn/sidebar', array('active' => 'overview'));
?>

<h1>学习</h1>
<p>
    无论你的偏好的设计板式或经验水平，我们有你正在寻找的文档。
</p>

<h2>入门指南</h2>

<p>
    我们的快速入门,将带你走进的使用过程中一些重要的Zend框架组件,而展示ZF2或ZF1应用程序如何从头构建的。
</p>

<ul class="button-group">
    <li><a href="<?php echo $this->basePath('manual/2.3/en/user-guide/overview.html') ?>" class="small button">Zend Framework 2</a></li>
    <li><a href="<?php echo $this->basePath('manual/1.12/en/learning.quickstart.html') ?>" class="small button">Zend Framework 1</a></li>
</ul>

<h2>参考指南</h2>

<p>
    超过1000页和500个案例,我们的参考指南补充质量代码与文档。</p>

<ul class="button-group">
    <li><a href="<?php echo $this->basePath('manual/2.3/en/index.html') ?>" class="small button">Zend Framework 2</a></li>
    <li><a href="<?php echo $this->basePath('manual/1.12/en/manual.html') ?>" class="small button">Zend Framework 1</a></li>
</ul>

<h2>API</h2>

<p>
   需找特定的方法？忘记常量的名字？使用Zend Framework's 完全自带的代码库，通过一些简单的点击操作，你能自己回答你所有的在API上的问题
</p>

<ul class="button-group">
    <li><a href="<?php echo $this->url('docs/api') ?>#zf2" class="small button">Zend Framework 2</a></li>
    <li><a href="<?php echo $this->url('docs/api') ?>#zf1" class="small button">Zend Framework 1</a></li>
</ul>

<h2>培训和认证</h2>

<p>
    专业的培训课程设计来源于Zend的领导者和
    Zend框架的社区. <a href="<?php echo $this->url('learn/training-and-certification') ?>">获取更多.</a>
</p>

<div class="row">
    <div class="three columns training">
        <a href="http://www.zend.com/en/services/training/zf2-fundamentals">
            <img src="<?php echo $this->basePath('/images/training-fundamentals.gif') ?>">
            <br>
            Zend Framework 2: 基础课程
        </a>
    </div>

    <div class="three columns training">
        <a href="http://www.zend.com/en/services/training/zf2-advanced-concepts">
            <img src="<?php echo $this->basePath('/images/training-advanced.gif') ?>">
            <br>
            Zend Framework 2: 高级课程
        </a>
    </div>

    <div class="three columns training">
        <a href="http://shop.zend.com/en/php-training/zend-framework2-training-certification-bundle.html">
            <img src="<?php echo $this->basePath('/images/training-bundle.gif') ?>">
            <br>
            ZF2 培训合集（优惠版）
        </a>
    </div>

    <div class="three columns training">
        <a href="http://shop.zend.com/en/zend-certification/zend-framework-certification-voucher.html">
            <img src="<?php echo $this->basePath('/images/training-certification.gif') ?>">
            <br>
            获取ZF2证书
        </a>
    </div>
</div>

<h2>支持 &amp; 咨询</h2>

<p>
    Zend为Zend框架通过Zend Server提供支持。此外, 　　Zend为PHP提供各种咨询服务和Zend框架。
    <a href="<?php echo $this->url('learn/training-and-certification') ?>">获取更多.</a>
</p>

<h2>在线研讨会</h2>

<p>

    从在线研讨会播客,你将能够找到演讲,面试,以及如何选择你的首选设计板式。访问
    <a href="http://www.zend.com/en/company/events/">Zend的事件页面</a>
    查看即将到来的网络研讨会列表或<a href="http://www.zend.com/en/resources/webinars/framework">点击这里</a>观看记录网络研讨会。


</p>

<hr />

<p>
    还没有找到你想要的?更多的文章可以在<a href="http://devzone.zend.com/category/zend-framework/">Zend DevZone</a>找到
</p>
