<?php
$this->render('downloads/downloads/sidebar', array('active' => 'composer'));

$headTitle = $this->headTitle();
$headTitle->prepend('下载');
$headTitle->prepend('Composer');
?>
<h1>使用Composer</h1>

<p>
    入门Zend Framework 2, 你可以使用<a href="http://getcomposer.org/">Composer</a>安装相关的软件以及依赖软件包.
    包是由我们的<a href="https://packages.zendframework.com/">packages.zendframework.com</a>管理.
</p>

<p>
    利用Composer使用我们的软件包, 添加相关的库信息到<code>composer.json</code>中即可:
</p>

<pre class="highlight javascript"><code>"repositories": [
    {
        "type": "composer",
        "url": "https://packages.zendframework.com/"
    }
],</code></pre>

<p>
    你可以添加任何你需要的软件包到你的列表,例如:
</p>

<pre class="highlight javascript"><code>"require": {
    "zendframework/zend-config": "2.0.*",
    "zendframework/zend-http": "2.0.*"
},</code></pre>

<p>
    运行安装命令下载依赖包:
</p>

<pre class="highlight bash"><code>php composer.phar install</code></pre>

<h2>可以用的软件包</h2>
    
<ul class="block-grid two-up mobile">
    <li>zendframework/zend-authentication</li>
    <li>zendframework/zend-barcode</li>
    <li>zendframework/zend-cache</li>
    <li>zendframework/zend-captcha</li>
    <li>zendframework/zendcloud</li>
    <li>zendframework/zend-code</li>
    <li>zendframework/zend-config</li>
    <li>zendframework/zend-console</li>
    <li>zendframework/zend-crypt</li>
    <li>zendframework/zend-db</li>
    <li>zendframework/zend-debug</li>
    <li>zendframework/zend-di</li>
    <li>zendframework/zend-dom</li>
    <li>zendframework/zend-escaper</li>
    <li>zendframework/zend-eventmanager</li>
    <li>zendframework/zend-feed</li>
    <li>zendframework/zend-file</li>
    <li>zendframework/zend-filter</li>
    <li>zendframework/zend-form</li>
    <li>zendframework/zendgdata</li>
    <li>zendframework/zend-http</li>
    <li>zendframework/zend-i18n</li>
    <li>zendframework/zend-inputfilter</li>
    <li>zendframework/zend-json</li>
    <li>zendframework/zend-ldap</li>
    <li>zendframework/zend-loader</li>
    <li>zendframework/zend-log</li>
    <li>zendframework/zend-mail</li>
    <li>zendframework/zend-math</li>
    <li>zendframework/zend-memory</li>
    <li>zendframework/zend-mime</li>
    <li>zendframework/zend-modulemanager</li>
    <li>zendframework/zend-mvc</li>
    <li>zendframework/zend-navigation</li>
    <li>zendframework/zendoauth</li>
    <li>zendframework/zendopenid</li>
    <li>zendframework/zend-paginator</li>
    <li>zendframework/zendpdf</li>
    <li>zendframework/zend-permissions-acl</li>
    <li>zendframework/zend-progressbar</li>
    <li>zendframework/zendrest</li>
    <li>zendframework/zend-serializer</li>
    <li>zendframework/zend-server</li>
    <li>zendframework/zendservice-agilezen</li>
    <li>zendframework/zendservice-akismet</li>
    <li>zendframework/zendservice-amazon</li>
    <li>zendframework/zendservice-gogrid</li>
    <li>zendframework/zendservice-livedocx</li>
    <li>zendframework/zend-servicemanager</li>
    <li>zendframework/zendservice-nirvanix</li>
    <li>zendframework/zendservice-rackspace</li>
    <li>zendframework/zendservice-recaptcha</li>
    <li>zendframework/zendservice-slideshare</li>
    <li>zendframework/zendservice-strikeiron</li>
    <li>zendframework/zendservice-technorati</li>
    <li>zendframework/zendservice-twitter</li>
    <li>zendframework/zendservice-windowsazure</li>
    <li>zendframework/zend-session</li>
    <li>zendframework/zend-soap</li>
    <li>zendframework/zend-stdlib</li>
    <li>zendframework/zend-tag</li>
    <li>zendframework/zend-text</li>
    <li>zendframework/zend-uri</li>
    <li>zendframework/zend-validator</li>
    <li>zendframework/zend-version</li>
    <li>zendframework/zend-view</li>
    <li>zendframework/zend-xmlrpc</li>
</ul>