<?php
$this->render('downloads/downloads/sidebar', array('active' => 'overview'));

$this->headTitle()->prepend('Downloads');
?>
<h1>下载</h1>

<h2>最新版本</h2>

<p>
    如果你在查找最新稳定版本Zend Framework,
    这里可以找到任何一个 1.X 或者 2.X的<a href="<?php echo $this->url('downloads', array('action' => 'latest')) ?>">最新版本</a>.
</p>

<p>
    为了下载方便, 我们设立CND网络, 提供了足够大的带宽服务.
</p>

<p>
    所有的版本提供zip(.zip)以及tarball(.tar.gz)两种压缩包下载.
</p>

<h2>下载ZF2文档文件</h2>

<p>
    你想使用便携设备读取文档?
</p>

<ul class="button-group">
    <li><a href="https://packages.zendframework.com/releases/ZendFramework-2.3.3/ZendFramework-2.3.3-manual-en.pdf" class="button">下载最新PDF</a></li>
    <li><a href="https://packages.zendframework.com/releases/ZendFramework-2.3.3/ZendFramework-2.3.3-manual-en.epub" class="button">下载最新EPUB</a></li>
</ul>

<h2>使用Composer或者Pyrus</h2>

<p>
    入门Zend Framework2,我们开始学习使用<a href="<?php echo $this->url('downloads', array('action' => 'composer')) ?>">Composer</a>或者
    <a href="<?php echo $this->url('downloads', array('action' => 'pyrus')) ?>">Pyrus</a>
    安装软件包或者整个框架程序.
</p>

<h2>获取核心程序</h2>

<p>
    我们提供了一个简化的ZF2项目程序,他提供了推荐的目录结构,配置文件,你可以通过<a href="http://getcomposer.org/">Composer</a>
    解决它的依赖关系.
</p>

<p>
    <a href="<?php echo $this->url('downloads', array('action' => 'skeleton-app')) ?>">马上获取核心程序!</a>
</p>

<h2>Git (Zend Framework 2.X)</h2>

<p>
    我们使用<a href="http://git-scm.org/">Git</a>开发Zend Framework2框架,如果你对源程序感兴趣, 你可以fork<a
        href="https://github.com/zendframework/zf2">我们在github的项目库</a>
</p>

<h2>Subversion (Zend Framework 1.X)</h2>

<p>
    如果你想通过svn获取ZF1, 请访问<a
        href="http://framework.zend.com/wiki/display/ZFDEV/Subversion+Standards">svn说明</a>.
</p>

<h2>合作下载</h2>

<p>
    最新版本的合作Zend组件下载.
</p>

<dl>
    <dt>谷歌数据API库 (Zend Framework 1.X)</dt>
    <dd>
        Zend_Gdata提供了一套基于PHP5实现的谷歌数据读写访问谷歌服务器接口,例如YouTube,Picasa,Blogger.
    </dd>

    <dt>微软信用卡库 (Zend Framework 1.X)</dt>
    <dd>
        Microsoft has partnered with Zend Technologies to bring support for
        Windows Cardspace and other InfoCard technologies to PHP 5 applications.
    </dd>

    <dt>Adobe AMF库 (Zend Framework 1.X)</dt>
    <dd>
        Adobe has contributed support for Action Message Format (AMF0 and
        AMF3) to Zend Framework.
    </dd>
</dl>

<h2>历史下载</h2>

<p>
    We've made every public release of Zend Framework, including the
    partner products, <a href="<?php echo $this->url('downloads', array('action' => 'archives'))
    ?>">available for download</a>.
</p>

