<?php
$this->render('downloads/downloads/sidebar', array('active' => 'latest'));

$headTitle = $this->headTitle();
$headTitle->prepend('Downloads');
$headTitle->prepend('Latest');

$zf2Version = $this->releases->getCurrentStableVersion(2);
$zf2Date    = $this->releases->getReleaseDate($zf2Version);

$zf1Version = $this->releases->getCurrentStableVersion(1);
$zf1Date    = $this->releases->getReleaseDate($zf1Version);
?>
<h1>最新版本</h1>

<ul class="button-group">
    <li><a href="#ZF2" class="button">ZF2版本</a></li>
    <li><a href="#ZF1" class="button">ZF1版本</a></li>
</ul>

<p>
   所有的最新版本都可以在这里找到.
</p>


<h2 id="ZF2">Zend Framework 2</h2>

<table class="twelve">
    <tr>
        <td class="alpha">
            <img src="<?php echo $this->basePath('/images/full_package_box.png') ?>" alt="Zend CDN" />
        </td>

        <td>
            <h4>Zend Framework全套软件包</h4>
            <p>
                如何你没有特殊的偏好使用CDN网络下载最新的软件包,包含所有的演示.
            </p>
        </td>

        <td class="omega">
            <a href="http://www.zend.com/company/community/framework/downloads" class="small button">免费下载</a>
        </td>
    </tr>

    <tr>
        <td class="alpha">&nbsp;</td>

        <td>
            <h4>Zend Framework <?php echo $zf2Version ?> 完整版本</h4>
            <p>发布时间 <?php echo $zf2Date ?></p>
        </td>

        <td class="omega">
            <div href="#" class="small button dropdown">
                下载
                <ul>
                    <li>
                        <a href="<?php echo $this->releases->getArchive($zf2Version, 'zip') ?>">zip</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->releases->getArchive($zf2Version, 'tar.gz') ?>">tar.gz</a>
                    </li>
                </ul>
            </div>
        </td>
    </tr>

    <tr>
        <td class="alpha">&nbsp;</td>

        <td>
            <h4>Zend Framework <?php echo $zf2Version ?> 文档</h4>
            <p>发布时间 <?php echo $zf2Date ?></p>
        </td>

        <td class="omega">

            <div href="#" class="small button dropdown">
                下载
                <ul>
                    <li>
                        <a href="<?php echo $this->url('learn', array(
                            'lang' => 'en',
                            'version' => $this->releases->getMinorVersion($zf2Version),
                        )) ?>">Browse</a>
                    </li>
                    <li class="divider"></li>
                    <?php
                    $zf2PackageBase = sprintf(
                        'http://packages.zendframework.com/releases/ZendFramework-%s/ZendFramework-%s-manual-en',
                        $zf2Version,
                        $zf2Version
                    );
                    printf("<li><a href=\"%s.pdf\">PDF</a></li>\n", $zf2PackageBase);
                    printf("<li><a href=\"%s.epub\">EPUB</a></li>\n", $zf2PackageBase);

                    echo $this->render('downloads/downloads/documentation-links', array(
                        'version'  => $zf2Version,
                        'id'       => 'zf2docslatest',
                        'releases' => $this->releases,
                    ));
                    ?>

                </ul>
            </div>
        </td>
    </tr>
</table>

<p>
    你也可以通过<a href="<?php echo $this->url(
        'downloads',
        array('action' => 'composer')
    ); ?>">Composer</a> 或者 <a href="<?php echo $this->url(
        'downloads',
        array('action' => 'pyrus')
    ); ?>">Pyrus</a>安装Zend Framework 2或者部分组件.
</p>

<h2 id="ZF1">Zend Framework 1</h2>

<table class="twelve">
    <tr>
        <td class="alpha">
            <img src="<?php echo $this->basePath('/images/full_package_box.png') ?>" alt="Zend CDN" />
        </td>

        <td>
            <h4>Zend Framework完整软件包</h4>
            <p>
                如何你没有特殊的偏好使用CDN网络下载最新的软件包,包含所有的演示.
            </p>
        </td>

        <td class="omega">
            <a href="http://www.zend.com/company/community/framework/downloads" class="small button">免费下载</a>
        </td>
    </tr>

    <tr>
        <td class="alpha">&nbsp;</td>

        <td>
            <h4>Zend Framework <?php echo $zf1Version ?> 完整软件包</h4>
            <p>发布时间 <?php echo $zf1Date ?></p>
        </td>

        <td class="omega">
            <div href="#" class="small button dropdown">
                下载
                <ul>
                    <li>
                        <a href="<?php echo $this->releases->getArchive($zf1Version, 'zip') ?>">zip</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->releases->getArchive($zf1Version, 'tar.gz') ?>">tar.gz</a>
                    </li>
                </ul>
            </div>
        </td>
    </tr>

    <tr>
        <td class="alpha">&nbsp;</td>

        <td>
            <h4>Zend Framework <?php echo $zf1Version ?> 最小版本</h4>
            <p>发布时间 <?php echo $zf1Date ?></p>
        </td>

        <td class="omega">
            <div href="#" class="small button dropdown">
                下载
                <ul>
                    <li>
                        <a href="<?php echo $this->releases->getMinimalArchive($zf1Version, 'zip') ?>">zip</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->releases->getMinimalArchive($zf1Version, 'tar.gz') ?>">tar.gz</a>
                    </li>
                </ul>
            </div>
        </td>
    </tr>

    <tr>
        <td class="alpha">&nbsp;</td>

        <td>
            <h4>Zend Framework <?php echo $zf1Version ?> 文档</h4>
            <p>发布时间 <?php echo $zf1Date ?></p>
        </td>

        <td class="omega">
            <div href="#" class="small button dropdown">
                下载
                <ul>
                    <li>
                        <a href="<?php echo $this->url('learn', array(
                            'lang' => 'en',
                            'version' => $this->releases->getMinorVersion($zf1Version),
                        )) ?>">Browse</a>
                    </li>
                    <li>
                        <?php
                            echo $this->render('downloads/downloads/documentation-links', array(
                                'version'  => $zf1Version,
                                'id'       => 'zf1docslatest',
                                'releases' => $this->releases,
                            ));
                        ?>
                    </li>
                </ul>
            </div>
        </td>
    </tr>
</table>

<h2>其他下载</h2>

<p>
    ZF1框架有少量的独立组建,每个链接的软件包里面包含软件代码,文档,测试,api等.
</p>

<table class="twelve">
    <tr>
        <td class="alpha product">
            <h4>Zend_Gdata</h4>

            <p>
                版本 <?php
                    $gdataVersion = $this->releases->getCurrentStableProductVersion('gdata');
                    echo $gdataVersion;
                ?>;<br />
                发布日期 <?php echo $this->releases->getReleaseDate($gdataVersion) ?>
            </p>

        </td>

        <td>
            <p>
                Zend_Gdata提供了一套基于PHP5实现的谷歌数据读写访问谷歌服务器接口
                要想了解更多,请访问
                <a href="http://code.google.com/apis/gdata/index.html">Google
                GData site</a>.
            </p>
        </td>

        <td class="omega">
            <div href="#" class="small button dropdown">
                下载
                <ul>
                    <li>
                        <a href="<?php echo $this->releases->getProductArchive(
                            'gdata',
                            $gdataVersion,
                            'zip'
                        ); ?>">zip</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->releases->getProductArchive(
                            'gdata',
                            $gdataVersion,
                            'tar.gz'
                        ); ?>">tar.gz</a>
                    </li>
                </ul>
            </div>
        </td>
    </tr>

    <tr>
        <td class="alpha product">
            <h4>Zend_InfoCard</h4>

            <p>
                版本 <?php
                    $infocardVersion = $this->releases->getCurrentStableProductVersion('infocard');
                    echo $infocardVersion;
                ?>;<br />
                发布日期 <?php echo $this->releases->getReleaseDate($infocardVersion) ?>
            </p>

        </td>

        <td>
            <p>
                微软和Zend提供信用卡技术支持,这将降低开发成本,使得网络更加安全.
            </p>

            <p>
                Users who access infocard-enabled web sites will receive
                consistent user control of their digital identities and
                improved confidence in the authentication process for
                remote applications, all with greater security than
                password-based Web logins offer. For consumers, Zend
                Technologies' implementation of information cards enables
                users to provide their digital identities in a familiar,
                security-enhanced and simple way. They are analogous to
                business cards, credit cards or membership cards that
                people use every day. Enabling information card support in
                Zend Framework allows developers to make it easy for users
                of their Web sites to use Windows Cardspace™ and other
                solutions to identify themselves without remembering myriad
                usernames and passwords, providing them with not just
                greater convenience, but much more security.
            </p>
        </td>

        <td class="omega">
            <div href="#" class="small button dropdown">
                下载
                <ul>
                    <li>
                        <a href="<?php echo $this->releases->getProductArchive(
                            'infocard',
                            $infocardVersion,
                            'zip'
                        ); ?>">zip</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->releases->getProductArchive(
                            'infocard',
                            $infocardVersion,
                            'tar.gz'
                        ); ?>">tar.gz</a>
                    </li>
                </ul>
            </div>
        </td>
    </tr>

    <tr>
        <td class="alpha product">
            <h4>Zend_AMF</h4>

            <p>
                版本 <?php
                    $amfVersion = $this->releases->getCurrentStableProductVersion('amf');
                    echo $amfVersion;
                ?>;<br />
                发布日期 <?php echo $this->releases->getReleaseDate($amfVersion) ?>
            </p>

        </td>

        <td>
            <p>
                Adobe Systems has contributed support for their open,
                binary Action Message Format (AMF) protocol to Zend Framework. Using Zend_Amf,
                you can build Flex and AIR applications that are performant and use minimal
                bandwidth. Zend_Amf supports both <a 
                    href="http://download.macromedia.com/pub/labs/amf/amf0_spec_121207.pdf">AMF0</a>
                and <a href="http://download.macromedia.com/pub/labs/amf/amf3_spec_121207.pdf">AMF3</a>.
            </p>
        </td>

        <td class="omega">
            <div href="#" class="small button dropdown">
                下载
                <ul>
                    <li>
                        <a href="<?php echo $this->releases->getProductArchive(
                            'amf',
                            $amfVersion,
                            'zip'
                        ); ?>">zip</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->releases->getProductArchive(
                            'amf',
                            $amfVersion,
                            'tar.gz'
                        ); ?>">tar.gz</a>
                    </li>
                </ul>
            </div>
        </td>
    </tr>
</table>
