<?php
$this->render('downloads/downloads/sidebar', array('active' => 'pyrus'));

$headTitle = $this->headTitle();
$headTitle->prepend('Downloads');
$headTitle->prepend('Pyrus');
?>
<h1>使用Pyrus</h1>

<p>如果你没有安装Pyrus请依照下面获取:</p>

<pre class="highlight bash"><code>wget https://packages.zendframework.com/pyrus.phar
</code></pre>

<p>使用pyrus安装ZF软件包你只需要在你的安装目录运行:</p>

<pre class="highlight bash"><code>$ pyrus.phar .
$ pyrus.phar . channel-discover packages.zendframework.com
$ pyrus.phar . install zf2/<zf-package>
</code></pre>

<p>
    如果<code>&lt;zf-package&gt;</code>是你需要安装的软件包,安装系统你也可以省略".",也可以指定一个路径安装,下面的软件包都可以安装, 例如:
</p>

<pre class="highlight bash"><code>$ pyrus.phar . install zf2/Zend_Http</code></pre>

<p>
    请使用"Zend_Framework"去安装完整稳定软件包. 例如:
</p>

<pre class="highlight bash"><code>$ pyrus.phar . install zf2/Zend_Framework#Standard</code></pre>

<p>
    如果你要安装一个非稳定版本软件包,请在<code>#</code>标签前面添加<code>-beta</code>, <code>-rc</code> 或者 <code>-devel</code>, 例如:
</p>

<pre class="highlight bash"><code>$ pyrus.phar . install zf2/Zend_Framework-beta#Standard</code></pre>

<h2>Available Packages</h2>

<ul class="block-grid two-up mobile">
    <li>zend_authentication</li>
    <li>zend_barcode</li>
    <li>zend_cache</li>
    <li>zend_captcha</li>
    <li>zendcloud</li>
    <li>zend_code</li>
    <li>zend_config</li>
    <li>zend_console</li>
    <li>zend_crypt</li>
    <li>zend_db</li>
    <li>zend_debug</li>
    <li>zend_di</li>
    <li>zend_dom</li>
    <li>zend_escaper</li>
    <li>zend_eventmanager</li>
    <li>zend_feed</li>
    <li>zend_file</li>
    <li>zend_filter</li>
    <li>zend_form</li>
    <li>Zend_Framework#Standard</li>
    <li>zendgdata</li>
    <li>zend_http</li>
    <li>zend_i18n</li>
    <li>zend_inputfilter</li>
    <li>zend_json</li>
    <li>zend_ldap</li>
    <li>zend_loader</li>
    <li>zend_log</li>
    <li>zend_mail</li>
    <li>zend_math</li>
    <li>zend_memory</li>
    <li>zend_mime</li>
    <li>zend_modulemanager</li>
    <li>zend_mvc</li>
    <li>zend_navigation</li>
    <li>zendoauth</li>
    <li>zendopenid</li>
    <li>zend_paginator</li>
    <li>zendpdf</li>
    <li>zend_permissions_acl</li>
    <li>zend_progressbar</li>
    <li>zendrest</li>
    <li>zend_serializer</li>
    <li>zend_server</li>
    <li>zendserviceagilezen</li>
    <li>zendserviceakismet</li>
    <li>zendserviceamazon</li>
    <li>zendserviceaudioscrobbler</li>
    <li>zendservicedelicious</li>
    <li>zendserviceflickr</li>
    <li>zendservicegogrid</li>
    <li>zendservicelivedocx</li>
    <li>zend_servicemanager</li>
    <li>zendservicenirvanix</li>
    <li>zendservicerackspace</li>
    <li>zendservicerecaptcha</li>
    <li>zendserviceslideshare</li>
    <li>zendservicestrikeiron</li>
    <li>zendservicetechnorati</li>
    <li>zendservicetwitter</li>
    <li>zendservicewindowsazure</li>
    <li>zend_session</li>
    <li>zend_soap</li>
    <li>zend_stdlib</li>
    <li>zend_tag</li>
    <li>zend_text</li>
    <li>zend_uri</li>
    <li>zend_validator</li>
    <li>zend_version</li>
    <li>zend_view</li>
    <li>zend_xmlrpc</li>
</ul>

<p class="panel">
    Pyrus is the PEAR2 installer; for more information, please visit the
    <a href="http://pear2.php.net/">PEAR2 and Pyrus website</a>. The version we include also includes the
    developer tools and simple channel service tools, which are typically
    not included in the standard Pyrus distribution, but which can be of
    use to those interested in creating and distributing packages.
</p>