<?php
$this->layout()->active = 'start';
$this->layout()->bodyId = 'downloads';

$this->placeholder('sidebar')->captureStart(); ?>
<ul>
    <li<?php echo ($this->active == 'overview' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('downloads') ?>">概述</a>
    </li>
    <li<?php echo ($this->active == 'latest' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('downloads', array('action' => 'latest')) ?>">最新版本</a>
    </li>
    <li<?php echo ($this->active == 'composer' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('downloads', array('action' => 'composer')) ?>">使用Composer</a>
    </li>
    <li<?php echo ($this->active == 'pyrus' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('downloads', array('action' => 'pyrus')) ?>">使用Pyrus</a>
    </li>
    <li<?php echo ($this->active == 'skeleton-app' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('downloads', array('action' => 'skeleton-app')) ?>">
            获取核心应用程序
        </a>
    </li>
    <li<?php echo ($this->active == 'archives' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('downloads', array('action' => 'archives')) ?>">历史版本</a>
    </li>
</ul>

<?php $this->placeholder('sidebar')->captureEnd(); ?>

