<?php
$this->render('downloads/downloads/sidebar', array('active' => 'skeleton-app'));

$headTitle = $this->headTitle();
$headTitle->prepend('下载');
$headTitle->prepend('核心程序');
?>
<h1>获取核心程序</h1>

<p>
    这个一个简单的基于ZF的MVC程序,该程序可用来入门学习ZF2.
</p>

<h2>安装</h2>

<h3>使用Composer (推荐)</h3>

<p>
    clone该项目的库后,推荐使用该方式安装该项目的依赖包:
</p>

<pre class="highlight bash"><code>cd my/project/dir
git clone git://github.com/zendframework/ZendSkeletonApplication.git
cd ZendSkeletonApplication
php composer.phar install</code></pre>

<p>
    除了clon项目, 你也可以直接下载<a
    href="https://github.com/zendframework/ZendSkeletonApplication/tarball/master">tarball</a>
    或者 <a href="https://github.com/zendframework/ZendSkeletonApplication/zipball/master">zipball</a> 压缩包到新目录,并且运行composer.
</p>

<h3>使用git子模块</h3>

<p>
    或者你可以使用Git的子模块直接安装:
</p>

<pre class="highlight bash"><code>git clone git://github.com/zendframework/ZendSkeletonApplication.git --recursive
</code></pre>


<h2>测试</h2>

一但你下载了核心程序安装了, 你需要确保能够正常运行.

<h3>虚拟主机</h3>

<p>
    设置一个虚拟主机指向 "public/" 目录!
</p>

<h3>PHP 5.4以上版本内置服务器</h3>

<p>
    进入 "public/" 目录, 启动PHP WEB服务器, 你可以通过 "http://localhost:8888/" 来访问项目, 例如:
</p>

<pre class="highlight bash"><code>cd public
php -S localhost:8888</code></pre>

<h2>下一步</h2>

<p>
    不知道下一步该干嘛?
    <a href="<?php echo $this->manualUrl('user-guide/overview.html') ?>">
        阅读用户向导!
    </a>
</p>
