<?php
$this->render('page-controller/contact/sidebar', array('active' => 'irc'));

$this->headTitle()->prepend('Contact');
$this->headTitle()->prepend('IRC');
?>
<h1>IRC</h1>

<p>
    　Zend的日常沟通和决策框架发生在互联网中继聊天(IRC)。许多频道可对于那些寻求帮助,以及那些感兴趣的人协助开发的框架。
</p>

<p>
    所有通道都在<a href="http://freenode.net/">Freenode IRC</a>.
</p>

<dl>
    <dt>#zftalk</dt>
    <dd>用于一般用途的问题和问题。</dd>

    <dt>#zftalk.dev</dt>
    <dd>讨论ZF的发展.</dd>
</dl>