<?php
$this->layout()->active = 'participate';
$this->layout()->bodyId = 'contact';

$this->placeholder('sidebar')->captureStart();
?>
<ul>
    <li<?php echo ($this->active == 'contact' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('contact') ?>">联系与建议</a>
    </li>
    <li<?php echo ($this->active == 'archives' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('archives') ?>">档案列表</a>
    </li>
    <li<?php echo ($this->active == 'subscribe' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('archives/subscribe') ?>">签约信息
        </a>
    </li>
    <li<?php echo ($this->active == 'irc' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('irc') ?>">IRC</a>
    </li>
</ul>
<?php $this->placeholder('sidebar')->captureEnd() ?>

