<?php
$this->layout()->bodyId = 'manual';
$this->layout()->active = 'learn';

$this->placeholder('sidebar')->captureStart(); ?>
<ul>
    <li<?php echo ($this->active == 'overview' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('learn') ?>">概述</a>
    </li>
    <li<?php echo ($this->active == 'training-and-certification' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('learn/training-and-certification') ?>">培训与认证</a>
    </li>
    <li<?php echo ($this->active == 'support-and-consulting' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->url('learn/support-and-consulting') ?>">支持与咨询</a>
    </li>
</ul>

<h1>Zend Framework 2</h1>
<ul>
    <li>
        <a href="<?php echo $this->basePath('manual/2.3/zh/user-guide/overview.html') ?>">入门</a>
    </li>
    <li>
        <a href="<?php echo $this->basePath('manual/2.3/zh/index.html') ?>">参考指南</a>
    </li>
    <li<?php echo ($this->active == 'api' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->basePath('docs/api#zf2') ?>">API</a>
    </li>
</ul>

<h1>Zend Framework 1</h1>
<ul>
    <li>
        <a href="<?php echo $this->basePath('manual/1.12/zh/learning.quickstart.html') ?>">入门</a>
    </li>
    <li>
        <a href="<?php echo $this->basePath('manual/1.12/zh/manual.html') ?>">参考指南</a>
    </li>
    <li<?php echo ($this->active == 'api' ? ' class="active"' : '') ?>>
        <a href="<?php echo $this->basePath('docs/api#zf1') ?>">API</a>
    </li>
</ul>

<div class="zf2a-course">
    <?php //echo $this->render('trainingads') ?>
</div>

<?php $this->placeholder('sidebar')->captureEnd(); ?>

