<?php
$this->render('manual/page-controller/learn/sidebar', array('active' => 'support-and-consulting'));

$headTitle = $this->headTitle();
$headTitle->prepend('学习');
$headTitle->prepend('支持与咨询');
?>
<h1>支持与咨询</h1>

<blockquote>
    降低业务与技术风险，使你安心的开发您的项目。
</blockquote>

<h2>支持</h2>

<p>
    Zend Framework提供了核心的技术支持，在整个项目周期为您提供帮助，有与提高开发人员的开发效率，同时降低项目部署时间，这些有效增为您的项目成功保驾护航。
</p>

<p>
    想了解更多信息请访问
    <a href="http://www.zend.com/en/support-center/support/">Zend支持</a>.
</p>

<h2>咨询</h2>

<p>
    无论是你是一个时间敏感的项目或者一个高度定制的组建，Zend提供PHP，Zend Framework自从， 了解更多请访问<a href="http://www.zend.com/en/services/consulting/">Zend咨询</a>。
</p>