<?php
$this->render('manual/page-controller/learn/sidebar', array('active' => 'training-and-certification'));

$headTitle = $this->headTitle();
$headTitle->prepend('培训');
$headTitle->prepend('培训与认证');
?>
<h1>培训与认证</h1>

<blockquote>
    学习Zend Framework
</blockquote>

<h2>培训</h2>

<dl class="training">
    <dt>
        <a href="http://www.zend.com/services/training/zf1-fundamentals?src=ZFsite">Zend Framework:基础培训</a>
    </dt>

    <dd>
        <p>
            <img class="icon" src="<?php echo $this->basePath('/images/training-fundamentals.gif') ?>">
            Zend框架:基础课程是专为有经验的PHP程序员利用PHP 5结合ZF概念和结构元素为开发应用的工具包
             <a href="http://www.zend.com/services/training/zf1-fundamentals?src=ZFsite">学习更多 &raquo;</a>
        </p>
    </dd>

    <dt>
        <a href="http://www.zend.com/services/training/zf2-fundamentals?src=ZFsite">Zend Framework 2: 基础培训(新!)</a>
    </dt>
    <dd>
        <p>
            <img class="icon" src="<?php echo $this->basePath('/images/training-fundamentals.gif') ?>">
            本课程是建立在实践活动和项目之上的,让有经验的PHP程序员开发Zend框架2的体系结构和概念的专业课程　　。
            <a href="http://www.zend.com/services/training/zf2-fundamentals?src=ZFsite">学习更多 &raquo;</a>
        </p>
    </dd>

    <dt>
        <a href="http://www.zend.com/en/services/training/zf1-advanced-concepts?src=ZFsite">Zend Framework: 进阶培训</a>
    </dt>
    <dd>
        <p>
            <img class="icon" src="<?php echo $this->basePath('/images/training-advanced.gif') ?>">
            在完成的过程中，活跃的PHP开发人员应掌握构建和配置Zend Framework1应用程序的可扩展性，交互性和高性能时采用的最佳做法
            <a href="http://www.zend.com/en/services/training/zf1-advanced-concepts?src=ZFsite">学习更多 &raquo;</a>
        </p>
    </dd>

    <dt>
        <a href="http://www.zend.com/en/services/training/zf2-advanced-concepts?src=ZFsite">Zend Framework 2: 专业培训</a>
    </dt>
    <dd>
        <p>
            <img class="icon" src="<?php echo $this->basePath('/images/training-advanced.gif') ?>">
            在完成的过程中，活跃的PHP开发者应该掌握建设和配置Zend框架2时采用最佳做法以及应用程序的可扩展性，交互性和高性能。
            <a href="http://www.zend.com/en/services/training/zf2-advanced-concepts?src=ZFsite">学习更多 &raquo;</a>
        </p>
    </dd>

    <dt>
        <a href="http://www.zend.com/services/training/test-prep-zf1-certification?src=ZFsite">测试准备:ZendFramework1认证培训</a>
    </dt>
    <dd>
        <p>
            <img class="icon" src="<?php echo $this->basePath('/images/training-certification.gif') ?>">
            Zend框架是一种行业标准认证承认的专业水平的成就，在Zend框架使用专业知识。这个认证也有一定程度的区别,雇主使用评估　　未来的员工。课程准备经验丰富，设计和构建PHP应用程序的开发人员使用ZF，通过认证考试的挑战和实现Zend认证工程师在Zend框架的(ZCE-ZF)。
            <a href="http://www.zend.com/services/training/test-prep-zf1-certification?src=ZFsite">学习更多 &raquo;</a>
        </p>
    </dd>

    <dt>
        <a href="http://www.zend.com/services/training/test-prep-zf2-certification?src=ZFsite">测试准备: Zend Framework 2 认证培训
        </a>
    </dt>
    <dd>
        <p>
            <img class="icon" src="<?php echo $this->basePath('/images/training-certification.gif') ?>">
            Zend框架2认证是一种行业标准承认的专业使用Zend框架2的专业知识水平。这个认证也一定程度的区别，雇主使用评估潜在的雇员。
            <a href="http://www.zend.com/services/training/test-prep-zf2-certification?src=ZFsite">学习更多 &raquo;</a>
        </p>
    </dd>

    <dt>
        <a href="http://www.zend.com/en/services/training/training-bundles?src=ZFsite"
            >特殊包提供——从 Zend框架中的 A-Zend</a>
    </dt>
    <dd>
        <p>
            <img class="icon" src="<?php echo $this->basePath('/images/training-bundle.gif') ?>">
            从Zend框架，并脱颖而出，成为一个Zend框架认证工程师。
                        该软件包包括以下课程，以折扣价：
        </p>

        <ul>
            <li>Zend Framework: 基本原理</li>
            <li>Zend Framework: 高级概念
            </li>
            <li>测试准备: Zend Framework认证考试</li>
            <li>zend Framework认证凭证</li>
        </ul>

        <p>
        <a href="http://www.zend.com/en/services/training/training-bundles?src=ZFsite"
            >学习更多 &raquo;</a>
        </p>
    </dd>

<h3>更多关于培训的问题?</h3>

<p>
    如果你有任何问题关于这些或其他Zend服务或产品的问题请 <a href="mailto:itraining@zend.com">联系我们</a>.
</p>


<h2>认证</h2>

<p>
    Zend认证工程师,您将加入的队伍给最好的，最聪明的工程师和Zend框架架构师。ZendFramework ZCE's 优势; Zend框架认证可以帮助你在竞争激烈的就业市场为PHP工程师在你目前的工作重新找一份新工作或升级你的责任。
</p>

<p>
    更多信息成为一个PHP Zend框架7月和其他证书,请访问
    <a href="http://www.zend.com/services/certification/">Zend认证中心 </a>.
</p>
